user_info = {
    "email1@example.com": "password1",
    "email2@example.com": "password2",
    "email3@example.com": "password3",
    "email4@example.com": "password4",
    "email5@example.com": "password5",
    "email6@example.com": "password6",
    "email7@example.com": "password7",
    "email8@example.com": "password8",
    "email9@example.com": "password9",
    "email10@example.com": "password10",
    "email11@example.com": "password11",
    "email12@example.com": "password12",
    "email13@example.com": "password13",
    "email14@example.com": "password14",
    "email15@example.com": "password15",
    "email16@example.com": "password16",
    "email17@example.com": "password17",
    "email18@example.com": "password18",
    "email19@example.com": "password19",
    "email20@example.com": "password20"
}
